name: Wasm Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libuv1-dev libssl-dev

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          submodules: recursive # This pulls in all the missing code parts

      - name: Build XMR-Wasm
        run: |
          # Check if we are in the right spot
          ls -R # This will log the folder structure so we can see where CMakeLists.txt is
          mkdir -p build && cd build
          emcmake cmake .. \
            -DXMRIG_WASM=ON \
            -DWITH_HTTPD=OFF \
            -DWITH_TLS=OFF \
            -DWITH_ADL=OFF \
            -DWITH_NVML=OFF \
            -DWITH_OPENCL=OFF \
            -DWITH_CUDA=OFF \
            -DCMAKE_BUILD_TYPE=Release
          emmake make -j2
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: wasm-payload
          path: |
            build/xmrig.js
            build/xmrig.wasm